/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit.
 * Vendored by hand for this external plugin (the DSH generator cannot see external
 * repos); kept in sync with host/src/types.ts. Shared sub-schemas are factored into
 * constants so the rule/view union only lives in one place.
 */
import { z } from 'zod'

const $id = z.intersection(z.string(), z.unknown())
const $status = z.union([z.literal("active"), z.literal("paused"), z.literal("completed")])
const $state = z.union([z.literal("scheduled"), z.literal("overdue"), z.literal("completed")])
const $model = z.object({
  'provider': z.string(),
  'model': z.string(),
})
const $errorCode = z.union([z.literal("invalid_title"), z.literal("invalid_prompt"), z.literal("invalid_selector"), z.literal("invalid_rule"), z.literal("invalid_time_zone"), z.literal("not_future"), z.literal("time_out_of_range"), z.literal("frequency_too_high"), z.literal("task_not_found"), z.literal("internal_error")])
const $failure = z.object({
  'ok': z.literal(false),
  'code': $errorCode,
  'message': z.string(),
})
const $rule = z.union([z.object({
  'kind': z.literal("after"),
  'afterSeconds': z.number(),
  'scheduledAt': z.string(),
}), z.object({
  'kind': z.literal("at"),
  'scheduledAt': z.string(),
}), z.object({
  'kind': z.literal("every"),
  'everySeconds': z.number(),
  'scheduledAt': z.string(),
}), z.object({
  'kind': z.literal("hourly"),
  'minute': z.number(),
  'scheduledAt': z.string(),
}), z.object({
  'kind': z.literal("daily"),
  'time': z.string(),
  'time_zone': z.string(),
  'scheduledAt': z.string(),
}), z.object({
  'kind': z.literal("weekly"),
  'weekdays': z.array(z.number()),
  'time': z.string(),
  'time_zone': z.string(),
  'scheduledAt': z.string(),
}), z.object({
  'kind': z.literal("monthly"),
  'dayOfMonth': z.number(),
  'time': z.string(),
  'time_zone': z.string(),
  'scheduledAt': z.string(),
})])
const $taskView = z.object({
  'id': $id,
  'title': z.string(),
  'prompt': z.string(),
  'rule': $rule,
  'status': $status,
  'sessionId': $id,
  'createdAt': z.string(),
  'lastRunAt': z.string().optional(),
  'nextRunAt': z.string().optional(),
  'lastError': z.object({
    at: z.string(),
    message: z.string().min(1),
  }).optional(),
  'state': $state,
  'unread': z.boolean(),
  'workspaceId': z.string().optional(),
  'cwd': z.string().optional(),
  'model': $model.optional(),
  'confirmBeforeChange': z.boolean(),
})
const $mutationResult = z.union([z.object({
  'ok': z.literal(true),
  'task': $taskView,
}), $failure])
const $carryFields = {
  'prompt': z.string().optional(),
  'workspaceId': z.string().optional(),
  'cwd': z.string().optional(),
  'model': $model.optional(),
  'confirmBeforeChange': z.boolean().optional(),
}
const $selectorFields = {
  'after_seconds': z.number().optional(),
  'at': z.object({
  'date': z.string(),
  'time': z.string(),
  'time_zone': z.string(),
}).optional(),
  'every_seconds': z.number().optional(),
  'hourly': z.object({
  'minute': z.number(),
}).optional(),
  'daily': z.object({
  'time': z.string(),
  'time_zone': z.string(),
}).optional(),
  'weekly': z.object({
  'weekdays': z.array(z.number()),
  'time': z.string(),
  'time_zone': z.string(),
}).optional(),
  'monthly': z.object({
  'dayOfMonth': z.number(),
  'time': z.string(),
  'time_zone': z.string(),
}).optional(),
}

const _deepseek_ai_dsh_scheduled_task_scheduledTasks_create_parameter_0$schema = z.object({
  'title': z.string(),
  ...$carryFields,
  ...$selectorFields,
})
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_create_result$schema = $mutationResult
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_delete_parameter_0$schema = $id
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_delete_result$schema = z.union([z.object({
  'ok': z.literal(true),
  'deleted': z.boolean(),
}), $failure])
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_list_result$schema = z.array($taskView)
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_markRead_parameter_0$schema = $id
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_markRead_result$schema = z.literal(null)
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_setStatus_parameter_0$schema = $id
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_setStatus_parameter_1$schema = z.union([z.literal("active"), z.literal("paused")])
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_setStatus_result$schema = $mutationResult
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_update_parameter_0$schema = $id
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_update_parameter_1$schema = z.object({
  'title': z.string().optional(),
  ...$carryFields,
  ...$selectorFields,
})
const _deepseek_ai_dsh_scheduled_task_scheduledTasks_update_result$schema = $mutationResult

export const TYPERT_REMOTE = {
  package: '@qihongmu/dsh-plugins-scheduled-task',
  descriptors: [
    {
      id: '@qihongmu/dsh-plugins-scheduled-task#scheduledTasks/create',
      service: 'scheduledTasks',
      namespace: 'scheduledTasks',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskCreateInput',
            schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_create_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskMutationResult',
        schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_create_result$schema,
      },
      sourceLocation: {"file":"packages/scheduled-task/host/src/index.ts","line":166,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-scheduled-task#scheduledTasks/delete',
      service: 'scheduledTasks',
      namespace: 'scheduledTasks',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskId',
            schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskDeleteResult',
        schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_delete_result$schema,
      },
      sourceLocation: {"file":"packages/scheduled-task/host/src/index.ts","line":244,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-scheduled-task#scheduledTasks/list',
      service: 'scheduledTasks',
      namespace: 'scheduledTasks',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-scheduled-task#scheduledTasks/list:result',
        schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_list_result$schema,
      },
      sourceLocation: {"file":"packages/scheduled-task/host/src/index.ts","line":151,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-scheduled-task#scheduledTasks/markRead',
      service: 'scheduledTasks',
      namespace: 'scheduledTasks',
      method: 'markRead',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskId',
            schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_markRead_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-scheduled-task#scheduledTasks/markRead:result',
        schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_markRead_result$schema,
      },
      sourceLocation: {"file":"packages/scheduled-task/host/src/index.ts","line":268,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-scheduled-task#scheduledTasks/setStatus',
      service: 'scheduledTasks',
      namespace: 'scheduledTasks',
      method: 'setStatus',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskId',
            schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_setStatus_parameter_0$schema,
          },
        },
        {
          name: 'status',
          wire: 'status',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskSettableStatus',
            schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_setStatus_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskMutationResult',
        schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_setStatus_result$schema,
      },
      sourceLocation: {"file":"packages/scheduled-task/host/src/index.ts","line":222,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-scheduled-task#scheduledTasks/update',
      service: 'scheduledTasks',
      namespace: 'scheduledTasks',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskId',
            schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_update_parameter_0$schema,
          },
        },
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskUpdateInput',
            schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_update_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-scheduled-task/types#ScheduledTaskMutationResult',
        schema: _deepseek_ai_dsh_scheduled_task_scheduledTasks_update_result$schema,
      },
      sourceLocation: {"file":"packages/scheduled-task/host/src/index.ts","line":200,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
