/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AttemptTrace, DayRollupView, RollupQuery, SessionRollupView, TokenTraceFrame, TurnTrace } from '@qihongmu/dsh-plugins-token-tracing/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$746f6b656e54726163696e67 {
    backfillAll: () => Promise<RemoteResult<{ processed: number }>>
    days: (query?: RollupQuery) => Promise<RemoteResult<DayRollupView[]>>
    follow: (sessionId: string, signal?: AbortSignal) => AsyncIterable<TokenTraceFrame>
    sessions: (query?: RollupQuery) => Promise<RemoteResult<SessionRollupView[]>>
    summary: (sessionId: string) => Promise<RemoteResult<SessionRollupView>>
    trace: (sessionId: string, turn: number) => Promise<RemoteResult<TurnTrace | null>>
    traceBatch: (sessionId: string, turns: readonly number[]) => Promise<RemoteResult<TurnTrace[]>>
  }
  interface TypertRemoteMap {
    'tokenTracing/backfillAll': () => Promise<RemoteResult<{ processed: number }>>
    'tokenTracing/days': (query?: RollupQuery) => Promise<RemoteResult<DayRollupView[]>>
    'tokenTracing/follow': (sessionId: string, signal?: AbortSignal) => AsyncIterable<TokenTraceFrame>
    'tokenTracing/sessions': (query?: RollupQuery) => Promise<RemoteResult<SessionRollupView[]>>
    'tokenTracing/summary': (sessionId: string) => Promise<RemoteResult<SessionRollupView>>
    'tokenTracing/trace': (sessionId: string, turn: number) => Promise<RemoteResult<TurnTrace | null>>
    'tokenTracing/traceBatch': (sessionId: string, turns: readonly number[]) => Promise<RemoteResult<TurnTrace[]>>
  }
  interface TypertRemoteNamespaceMap {
    'tokenTracing': TypertRemoteNamespace$746f6b656e54726163696e67
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
