/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit.
 * Vendored by hand for this external plugin (the DSH generator cannot see external
 * repos); kept in sync with host/src/types.ts and host/src/index.ts. Shared
 * sub-schemas are factored into constants so each union only lives in one place.
 * The `follow` descriptor is a hand-rolled stream method: `mode: 'stream'` +
 * `cancellation` + a per-item result codec, mirroring the in-repo generated
 * `session/follow` descriptor.
 */
import { z } from 'zod'

const $id = z.intersection(z.string(), z.unknown())
const $usage = z.object({
  'inputTokens': z.number().int().min(0),
  'outputTokens': z.number().int().min(0),
  'totalTokens': z.number().int().min(0),
  'cacheReadTokens': z.number().int().min(0).optional(),
  'cacheWriteTokens': z.number().int().min(0).optional(),
  'reasoningTokens': z.number().int().min(0).optional(),
})
const $componentKind = z.union([
  z.literal("user-input"), z.literal("injected-context"), z.literal("runtime-context"),
  z.literal("system-prompt"), z.literal("tool-definitions"), z.literal("tool-result"),
  z.literal("assistant-output"), z.literal("reasoning"), z.literal("compaction"),
  z.literal("context-shrink"), z.literal("unattributed"),
])
const $basis = z.union([z.literal("exact"), z.literal("estimated")])
const $componentSplit = z.object({
  'kind': $componentKind,
  'name': z.string().optional(),
  'tokens': z.number(),
  'basis': $basis,
})
const $cacheInfo = z.object({
  'read': z.number(),
  'write': z.number(),
  'hitRatio': z.number(),
})
const $cacheEvent = z.object({
  'atSeq': z.number(),
  'kind': z.union([z.literal("invalidated"), z.literal("compacted")]),
})
const $attemptTrace = z.object({
  'seq': z.number(),
  'turn': z.number(),
  'step': z.number(),
  'time': z.number().optional(),
  'kind': z.union([z.literal("llm"), z.literal("compaction")]),
  'retry': z.literal(true).optional(),
  'interrupted': z.literal(true).optional(),
  'usage': z.union([$usage, z.null()]),
  'promptTotal': z.union([z.number(), z.null()]),
  'composition': z.union([z.array($componentSplit), z.null()]),
  'additions': z.union([z.array($componentSplit), z.null()]),
  'cache': z.union([$cacheInfo, z.null()]),
  'invalidated': z.literal(true).optional(),
})
const $turnTrace = z.object({
  'sessionId': $id,
  'turn': z.number(),
  'status': z.union([z.literal("active"), z.literal("complete"), z.literal("incomplete")]),
  'startedAt': z.number(),
  'endedAt': z.union([z.number(), z.null()]),
  'attempts': z.array($attemptTrace),
  'totals': z.union([$usage, z.null()]),
  'cacheEvents': z.array($cacheEvent),
})
const $contribution = z.object({
  'turns': z.number(),
  'incompleteTurns': z.number(),
  'totals': $usage,
  'byComponent': z.record(z.string(), z.number()),
  'byTool': z.record(z.string(), z.number()),
})
const $sessionRollup = z.object({
  'sessionId': $id,
  'sessionCreatedAt': z.number(),
  'engine': z.number().optional(),
  'lastSeq': z.number(),
  'latestTurn': z.number().optional(),
  'turns': z.number(),
  'incompleteTurns': z.number(),
  'totals': $usage,
  'byComponent': z.record(z.string(), z.number()),
  'byTool': z.record(z.string(), z.number()),
  'byDay': z.record(z.string(), $contribution),
  'firstAt': z.number(),
  'lastAt': z.number(),
})
const $dayRollup = z.object({
  'day': z.string(),
  'sessions': z.number(),
  'turns': z.number(),
  'incompleteTurns': z.number(),
  'totals': $usage,
  'byComponent': z.record(z.string(), z.number()),
  'byTool': z.record(z.string(), z.number()),
})
const $query = z.object({
  'limit': z.number().optional(),
  'sinceDays': z.number().optional(),
})
const $frame = z.union([
  z.object({
    'kind': z.literal("snapshot"),
    'summary': $sessionRollup,
    'activeTurn': z.union([$turnTrace, z.null()]),
  }),
  z.object({
    'kind': z.literal("turn"),
    'trace': $turnTrace,
  }),
  z.object({
    'kind': z.literal("attempt"),
    'sessionId': $id,
    'attempt': $attemptTrace,
  }),
])

const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_backfillAll_result$schema = z.object({
  'processed': z.number(),
})
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_days_parameter_0$schema = $query
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_days_result$schema = z.array($dayRollup)
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_follow_parameter_0$schema = $id
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_follow_result$schema = $frame
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_sessions_parameter_0$schema = $query
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_sessions_result$schema = z.array($sessionRollup)
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_summary_parameter_0$schema = $id
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_summary_result$schema = $sessionRollup
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_trace_parameter_0$schema = $id
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_trace_parameter_1$schema = z.number()
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_trace_result$schema = z.union([$turnTrace, z.null()])
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_traceBatch_parameter_0$schema = $id
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_traceBatch_parameter_1$schema = z.array(z.number())
const _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_traceBatch_result$schema = z.array($turnTrace)

export const TYPERT_REMOTE = {
  package: '@qihongmu/dsh-plugins-token-tracing',
  descriptors: [
    {
      id: '@qihongmu/dsh-plugins-token-tracing#tokenTracing/backfillAll',
      service: 'tokenTracing',
      namespace: 'tokenTracing',
      method: 'backfillAll',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#processed',
        schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_backfillAll_result$schema,
      },
      sourceLocation: {"file":"packages/token-tracing/host/src/index.ts","line":335,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-token-tracing#tokenTracing/days',
      service: 'tokenTracing',
      namespace: 'tokenTracing',
      method: 'days',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'query',
          wire: 'query',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#RollupQuery',
            schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_days_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#DayRollupView',
        schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_days_result$schema,
      },
      sourceLocation: {"file":"packages/token-tracing/host/src/index.ts","line":284,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-token-tracing#tokenTracing/follow',
      service: 'tokenTracing',
      namespace: 'tokenTracing',
      method: 'follow',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#sessionId',
            schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_follow_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#TokenTraceFrame',
        schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_follow_result$schema,
      },
      sourceLocation: {"file":"packages/token-tracing/host/src/index.ts","line":297,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-token-tracing#tokenTracing/sessions',
      service: 'tokenTracing',
      namespace: 'tokenTracing',
      method: 'sessions',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'query',
          wire: 'query',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#RollupQuery',
            schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_sessions_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#SessionRollupView',
        schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_sessions_result$schema,
      },
      sourceLocation: {"file":"packages/token-tracing/host/src/index.ts","line":204,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-token-tracing#tokenTracing/summary',
      service: 'tokenTracing',
      namespace: 'tokenTracing',
      method: 'summary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#sessionId',
            schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_summary_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#SessionRollupView',
        schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_summary_result$schema,
      },
      sourceLocation: {"file":"packages/token-tracing/host/src/index.ts","line":219,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-token-tracing#tokenTracing/trace',
      service: 'tokenTracing',
      namespace: 'tokenTracing',
      method: 'trace',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#sessionId',
            schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_trace_parameter_0$schema,
          },
        },
        {
          name: 'turn',
          wire: 'turn',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#turn',
            schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_trace_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#TurnTrace',
        schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_trace_result$schema,
      },
      sourceLocation: {"file":"packages/token-tracing/host/src/index.ts","line":231,"column":3},
    },
    {
      id: '@qihongmu/dsh-plugins-token-tracing#tokenTracing/traceBatch',
      service: 'tokenTracing',
      namespace: 'tokenTracing',
      method: 'traceBatch',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#sessionId',
            schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_traceBatch_parameter_0$schema,
          },
        },
        {
          name: 'turns',
          wire: 'turns',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#turns',
            schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_traceBatch_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qihongmu/dsh-plugins-token-tracing/types#TurnTrace',
        schema: _deepseek_ai_dsh_plugins_token_tracing_tokenTracing_traceBatch_result$schema,
      },
      sourceLocation: {"file":"packages/token-tracing/host/src/index.ts","line":244,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
