/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ScheduledTaskCreateInput, ScheduledTaskDeleteResult, ScheduledTaskId, ScheduledTaskMutationResult, ScheduledTaskSettableStatus, ScheduledTaskUpdateInput, ScheduledTaskView } from '@qihongmu/dsh-plugins-scheduled-task/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7363686564756c65645461736b73 {
    create: (input: ScheduledTaskCreateInput) => Promise<RemoteResult<ScheduledTaskMutationResult>>
    delete: (id: ScheduledTaskId) => Promise<RemoteResult<ScheduledTaskDeleteResult>>
    list: () => Promise<RemoteResult<ScheduledTaskView[]>>
    markRead: (id: ScheduledTaskId) => Promise<RemoteResult<null>>
    setStatus: (id: ScheduledTaskId, status: ScheduledTaskSettableStatus) => Promise<RemoteResult<ScheduledTaskMutationResult>>
    update: (id: ScheduledTaskId, input: ScheduledTaskUpdateInput) => Promise<RemoteResult<ScheduledTaskMutationResult>>
  }
  interface TypertRemoteMap {
    'scheduledTasks/create': (input: ScheduledTaskCreateInput) => Promise<RemoteResult<ScheduledTaskMutationResult>>
    'scheduledTasks/delete': (id: ScheduledTaskId) => Promise<RemoteResult<ScheduledTaskDeleteResult>>
    'scheduledTasks/list': () => Promise<RemoteResult<ScheduledTaskView[]>>
    'scheduledTasks/markRead': (id: ScheduledTaskId) => Promise<RemoteResult<null>>
    'scheduledTasks/setStatus': (id: ScheduledTaskId, status: ScheduledTaskSettableStatus) => Promise<RemoteResult<ScheduledTaskMutationResult>>
    'scheduledTasks/update': (id: ScheduledTaskId, input: ScheduledTaskUpdateInput) => Promise<RemoteResult<ScheduledTaskMutationResult>>
  }
  interface TypertRemoteNamespaceMap {
    'scheduledTasks': TypertRemoteNamespace$7363686564756c65645461736b73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
